#######################################################
#
#    Aland Sailing Robot
#    ===========================================
#    test
#    -------------------------------------------
#
#	The top level makefile will export the following:
#		CXX: The C++ compiler to use
#		CC: THe C compiler to use
#		CPPFLAGS: C++ compiler flags
#		CFLAGS: C compiler flags
#		OBJECT_FILE: Path to the objects file containing all the boats objects
#
#######################################################



#######################################################
# Files
#######################################################

INT_TEST_FOLDER=./tests

INT_TEST_CV7 = cv7.c
INT_TEST_GPS = gps.c
INT_TEST_I2C = i2c_backend.c


INT_TESTS = $(INT_TEST_CV7) $(INT_TEST_GPS) $(INT_TEST_I2C)

OBJECT_C_FILE=build/library/nmea/nmea.o build/library/ptmx/ptmx.o \
	build/library/cv7serial/cv7serial.o build/library/i2c_backend/handler.o


INT_TEST_LIST = $(addprefix $(INT_TEST_FOLDER)/, $(INT_TESTS))

INTEGRATION_TESTS = $(addprefix $(INT_TEST_FOLDER)/output/, $(INT_TESTS:.c=.run))


#######################################################
# Rules
#######################################################


.PHONY: clean

all:$(INTEGRATION_TESTS)


# Compile C files into the build folder
$(INT_TEST_FOLDER)/output/%.run:$(INT_TEST_FOLDER)/%.c
	@mkdir -p $(dir $@)
	@echo Building test $@
	$(CC) $(CFLAGS) $(INC) -o ./$@ $< $(OBJECT_C_FILE) $(LIBS)

clean:
	@rm -rf $(INT_TEST_FOLDER)/output/
